services:

  backend:
    build:
      context: ./backend

    container_name: credit-api

    ports:
      - "3000:3000"

    restart: always

    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: Examen
      JWT_SECRET: your_secret_key

  frontend:
    build:
      context: ./frontend

    container_name: credit-front

    ports:
      - "4200:80"

    depends_on:
      - backend